# makefile for my idea that maybe i can "make" instead of "rosmake", just to troubleshoot

all:
	g++ TopDownView.cpp /home/stephanie/code/dev_stacks/kinect/OpenNI/Include/XnCppWrapper.h /home/stephanie/drivers/nite/build/Nite-1.3.1.5/Include/XnVNite.h -o topdown_out

# this is totally not working
